# Generated by Django 4.1.3 on 2023-02-22 02:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_address_is_default'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='vehicle',
            unique_together={('year', 'make', 'model')},
        ),
    ]
