# Generated by Django 4.1.3 on 2023-02-23 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_alter_vehicle_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='sent',
            field=models.DateTimeField(null=True),
        ),
    ]
