# Generated by Django 4.1.3 on 2023-02-23 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_user_sent'),
    ]

    operations = [
        migrations.AddField(
            model_name='tempuser',
            name='sent',
            field=models.DateTimeField(null=True),
        ),
    ]
