# Generated by Django 4.1.3 on 2023-03-30 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_tempuser_sent'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='model_code',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
