# Generated by Django 4.1.3 on 2023-08-02 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0007_vehicle_model_code"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="otp",
        ),
        migrations.RemoveField(
            model_name="user",
            name="otp_verified",
        ),
        migrations.RemoveField(
            model_name="user",
            name="sent",
        ),
        migrations.AddField(
            model_name="user",
            name="address",
            field=models.CharField(
                blank=True, default="null", max_length=255, null=True
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="mobile_number",
            field=models.CharField(default="null", max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name="user",
            name="password",
            field=models.CharField(max_length=8, null=True),
        ),
    ]
