# Generated by Django 4.1.3 on 2023-03-01 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0002_companysocials'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='companysocials',
            options={'verbose_name_plural': 'Company Social Accounts'},
        ),
        migrations.AddField(
            model_name='companysocials',
            name='whatsApp',
            field=models.URLField(default=None, verbose_name='WhatsApp'),
        ),
    ]
