# Generated by Django 4.1.3 on 2023-03-01 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0003_alter_companysocials_options_companysocials_whatsapp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companysocials',
            name='facebook',
            field=models.URLField(blank=True, null=True, verbose_name='Facebook'),
        ),
        migrations.AlterField(
            model_name='companysocials',
            name='instagram',
            field=models.URLField(blank=True, null=True, verbose_name='Instagram'),
        ),
        migrations.AlterField(
            model_name='companysocials',
            name='linkedIn',
            field=models.URLField(blank=True, null=True, verbose_name='LinkedIn'),
        ),
        migrations.AlterField(
            model_name='companysocials',
            name='twitter',
            field=models.URLField(blank=True, null=True, verbose_name='Twitter'),
        ),
        migrations.AlterField(
            model_name='companysocials',
            name='whatsApp',
            field=models.URLField(blank=True, default=None, null=True, verbose_name='WhatsApp'),
        ),
        migrations.AlterField(
            model_name='companysocials',
            name='youtube',
            field=models.URLField(blank=True, null=True, verbose_name='Youtube'),
        ),
    ]
