# Generated by Django 4.1.3 on 2023-03-09 01:43

import cms.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0004_alter_companysocials_facebook_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DealsBanner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=35)),
                ('sub_title', models.CharField(max_length=70)),
                ('text_color', models.CharField(choices=[('orange', 'orange'), ('black', 'black')], default=('orange', 'orange'), max_length=10)),
                ('image', models.ImageField(blank=True, upload_to=cms.models.banner_image_path)),
            ],
        ),
    ]
