# Generated by Django 4.1.3 on 2023-03-11 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0005_dealsbanner'),
    ]

    operations = [
        migrations.AddField(
            model_name='dealsbanner',
            name='category_tag',
            field=models.CharField(default='Engine', max_length=50),
        ),
    ]
