# Generated by Django 4.1.3 on 2023-05-02 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cms", "0006_dealsbanner_category_tag"),
    ]

    operations = [
        migrations.CreateModel(
            name="UploadImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("image", models.ImageField(upload_to="images/")),
            ],
        ),
    ]
