# Generated by Django 4.1.3 on 2023-08-02 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cms", "0007_uploadimage"),
    ]

    operations = [
        migrations.AlterField(
            model_name="uploadimage",
            name="image",
            field=models.CharField(max_length=100),
        ),
    ]
