# Generated by Django 4.1.3 on 2023-02-28 03:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='delivery_status',
            field=models.CharField(choices=[('I', 'in progress'), ('S', 'shipped'), ('D', 'delivered'), ('C', 'cancelled')], default='I', max_length=1),
        ),
    ]
